name: Main
on:
  push:
    branches: [ main, prod ]
jobs:
  deploy-dev:
    if: ${{ github.ref == 'refs/heads/main' }}
    uses: "./.github/workflows/build.yml"
    secrets: inherit
    with:
      environment: development
      db-schema: development
      debug: true
  deploy-prod:
    if: ${{ github.ref == 'refs/heads/prod' }}
    uses: "./.github/workflows/build.yml"
    secrets: inherit
    with:
      environment: production
      db-schema: public
      debug: false
